version: "3"
services:
  back-end-savedata:
    build:
      dockerfile: Dockerfile
      context: ./back-end-saveData
    container_name: app_backend_saveData
    volumes:
      - /app/node_modules
      - ./back-end-saveData:/app
      - ./.env:/app
    ports: 
      - "5001:5000"

  back-end-service:
    build:
      dockerfile: Dockerfile
      context: ./back-end-service
    container_name: app_backend_service
    volumes:
      - /app/node_modules
      - ./back-end-service:/app
      - ./.env:/app
    ports: 
      - "5000:5000"