version: "3"
services:

  back-end-savedata:
    build:
      dockerfile: Dockerfile
      context: ./back-end-saveData
    container_name: backend_saveData
    volumes:
      - /app/node_modules
      - ./back-end-saveData:/app
    ports: 
      - "5001:5000"

  back-end-service:
    build:
      dockerfile: Dockerfile
      context: ./back-end-service
    container_name: backend_service
    volumes:
      - /app/node_modules
      - ./back-end-service:/app
    ports: 
      - "5000:5000"

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./front-end
    volumes:
      - /app/node_modules
      - ./front-end:/app

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"
