let perks = [
    {style:8100,Name:"지배",engName:"Domination"},
    {perk:8112,Name:"감전",engName:"Electrocute"},
    {perk:8124,Name:"포식자",engName:"Predator"},
    {perk:8128,Name:"어둠의 수확",engName:"DarkHarvest"},
    {perk:9923,Name:"칼날비",engName:"HailOfBlades"},
    {perk:8126,Name:"비열한 한 방",engName:"CheapShot"},
    {perk:8139,Name:"피의 맛",engName:"GreenTerror_TasteOfBlood"},
    {perk:8143,Name:"돌발 일격",engName:"SuddenImpact"},
    {perk:8136,Name:"좀비 와드",engName:"ZombieWard"},
    {perk:8120,Name:"유령 포로",engName:"GhostPoro"},
    {perk:8138,Name:"사냥의 증표",engName:""},
    {perk:8135,Name:"보물 사냥꾼",engName:"TreasureHunter"},
    {perk:8134,Name:"영리한 사냥꾼",engName:"IngeniousHunter"},
    {perk:8105,Name:"끈질긴 사냥꾼",engName:"RelentlessHunter"},
    {perk:8106,Name:"궁극의 사냥꾼",engName:"UltimateHunter"},
    {perk:"????",Name:"시야 수집",engName:"EyeballCollection"},
    
    {style:8300,Name:"영감",engName:"Inspiration"},
    {perk:8351,Name:"빙결 강화",engName:"GlacialAugment"},
    {perk:8360,Name:"봉인 풀린 주문서",engName:"UnsealedSpellbook"},
    {perk:8369,Name:"선제공격",engName:"FirstStrike"},
    {perk:8306,Name:"마법공학 점멸기",engName:"HextechFlashtraption"},
    {perk:8304,Name:"마법의 신발",engName:"MagicalFootwear"},
    {perk:8313,Name:"완벽한 타이밍",engName:"PerfectTiming"},
    {perk:8321,Name:"외상",engName:"FuturesMarket"},
    {perk:8316,Name:"미니언 해체분석기",engName:"MinionDematerializer"},
    {perk:8345,Name:"비스킷 배달",engName:"BiscuitDelivery"},
    {perk:8347,Name:"우주적 통찰력",engName:"CosmicInsight"},
    {perk:8410,Name:"쾌속 접근",engName:"ApproachVelocity"}, //이거 Resolve에 들어있음
    {perk:8352,Name:"시간 왜곡 물약",engName:"TimeWarpTonic"},

    {style:8000,Name:"정밀",engName:"Precision"},
    {perk:8005,Name:"집중 공격",engName:"PressTheAttack"},
    {perk:8008,Name:"치명적 속도",engName:"LethalTempo"},
    {perk:8021,Name:"기민한 발놀림",engName:"FleetFootwork"},
    {perk:8010,Name:"정복자",engName:"Conqueror"},
    {perk:9101,Name:"과다치유",engName:"Overheal"},
    {perk:9111,Name:"승전보",engName:"Triumph"},
    {perk:8009,Name:"침착",engName:"PresenceOfMind"},
    {perk:9104,Name:"전설: 민첩함",engName:"LegendAlacrity"},
    {perk:9105,Name:"전설: 강인함",engName:"LegendTenacity"},
    {perk:9103,Name:"전설: 핏빛 길",engName:"LegendBloodline"},
    {perk:8014,Name:"최후의 일격",engName:"CoupDeGrace"},
    {perk:8017,Name:"체력차 극복",engName:"CutDown"},
    {perk:8299,Name:"최후의 저항",engName:"LastStand"}, //sorcery

    {style:8400,Name:"결의",engName:"Resolve"},
    {perk:8437,Name:"착취의 손아귀",engName:"GraspOfTheUndying"},
    {perk:8439,Name:"여진",engName:"VeteranAftershock"},
    {perk:8465,Name:"수호자",engName:"Guardian"},
    {perk:8446,Name:"철거",engName:"Demolish"},
    {perk:8463,Name:"생명의 샘",engName:"FontOfLife"},
    {perk:8401,Name:"보호막 강타",engName:"MirrorShell"},
    {perk:8429,Name:"사전 준비",engName:"Conditioning"},
    {perk:8444,Name:"재생의 바람",engName:"SecondWind"},
    {perk:8473,Name:"뼈 방패",engName:"BonePlating"},
    {perk:8451,Name:"과잉성장",engName:"Overgrowth"},
    {perk:8453,Name:"소생",engName:"Revitalize"},
    {perk:8242,Name:"불굴의 의지",engName:"Unflinching"}, //Sorcery

    {style:8200,Name:"마법",engName:"Sorcery"},
    {perk:8214,Name:"콩콩이 소환",engName:"SummonAery"},
    {perk:8229,Name:"신비로운 유성",engName:"ArcaneComet"},
    {perk:8230,Name:"난입",engName:"PhaseRush"},
    {perk:8224,Name:"무효화 구체",engName:"Pokeshield"},
    {perk:8226,Name:"마나순환 팔찌",engName:"ManaflowBand"},
    {perk:8210,Name:"깨달음",engName:"Transcendence"},
    {perk:8234,Name:"기민함",engName:"Celerity"},
    {perk:8233,Name:"절대 집중",engName:"AbsoluteFocus"},
    {perk:8237,Name:"주문 작열",engName:"Scorch"},
    {perk:8232,Name:"물 위를 걷는 자",engName:"Waterwalking"},
    {perk:8236,Name:"폭풍의 결집",engName:"GatheringStorm"},
]